# Generated by Django 4.1.4 on 2023-03-30 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customauth', '0002_alter_customuser_guild'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='motto',
            field=models.CharField(default='', max_length=1),
        ),
    ]
