# Generated by Django 4.1.4 on 2023-03-30 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customauth', '0003_customuser_motto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='guild',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='motto',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
